// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ViwHMHz7iOt1GOqSSSmT2VKGBYkBtQk',
    appId: '1:802038647784:web:d3fb6e86c89386fa74725d',
    messagingSenderId: '802038647784',
    projectId: 'chatting-app-flutter-4c092',
    authDomain: 'chatting-app-flutter-4c092.firebaseapp.com',
    storageBucket: 'chatting-app-flutter-4c092.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsw9_W7JIDcBcOU4qUO41S9FqDsZeoLro',
    appId: '1:802038647784:android:15790a0c509458ac74725d',
    messagingSenderId: '802038647784',
    projectId: 'chatting-app-flutter-4c092',
    storageBucket: 'chatting-app-flutter-4c092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAoYO3fTkMyY6iXudA4E_yAFoN7O2W2XY',
    appId: '1:802038647784:ios:96f906883d4b99a374725d',
    messagingSenderId: '802038647784',
    projectId: 'chatting-app-flutter-4c092',
    storageBucket: 'chatting-app-flutter-4c092.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSession',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAoYO3fTkMyY6iXudA4E_yAFoN7O2W2XY',
    appId: '1:802038647784:ios:96f906883d4b99a374725d',
    messagingSenderId: '802038647784',
    projectId: 'chatting-app-flutter-4c092',
    storageBucket: 'chatting-app-flutter-4c092.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSession',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5ViwHMHz7iOt1GOqSSSmT2VKGBYkBtQk',
    appId: '1:802038647784:web:8ef3d884b35109b474725d',
    messagingSenderId: '802038647784',
    projectId: 'chatting-app-flutter-4c092',
    authDomain: 'chatting-app-flutter-4c092.firebaseapp.com',
    storageBucket: 'chatting-app-flutter-4c092.firebasestorage.app',
  );
}
